[build]
builder = "DOCKERFILE"
# Tidak perlu buildCommand di sini, karena sudah diatur di Dockerfile
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn app:app"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[envs]
PYTHON_VERSION = "3.11.0"
NIXPACKS_PYTHON_VERSION = "3.11.0" 
